/*
  Sketch generated by the Arduino IoT Cloud Thing

  Arduino IoT Cloud Properties description

  The following variables are automatically generated and updated when changes are made to the Thing properties

  float humidity;
  int light;
  float temperature;

  Properties which are marked as READ/WRITE in the Cloud Thing will also have functions
  which are called when their values are changed from the Dashboard.
  These functions are generated with the Thing and added at the end of this sketch.
*/
#include <Adafruit_Sensor.h>  //for sensor
#include <DHT.h>            //for sensor
#include <DHT_U.h>

#include "thingProperties.h"

#define LEDPIN 2
#define DHTPIN 5
#define DHTTYPE DHT11
DHT dht(DHTPIN, DHTTYPE);


void setup() {
  // Initialize serial and wait for port to open:
  Serial.begin(9600);
  // This delay gives the chance to wait for a Serial Monitor without blocking if none is found
  delay(1500);

  // Defined in thingProperties.h
  initProperties();

  // Connect to Arduino IoT Cloud
  ArduinoCloud.begin(ArduinoIoTPreferredConnection);    //initializes Arduino Cloud

  /*
     The following function allows you to obtain more information
     related to the state of network and IoT Cloud connection and errors
     the higher number the more granular information you’ll get.
     The default is 0 (only errors).
     Maximum is 4
  */
  setDebugMessageLevel(2);
  ArduinoCloud.printDebugInfo();
  pinMode(LEDPIN, OUTPUT);
  dht.begin();      //initializes DHT sensor

}

void loop() {
  ArduinoCloud.update();    //updates Arduino Cloud to check for values
  onTemperatureChange();
  onHumidityChange();

}


void onLightChange()
{

  analogWrite(LEDPIN, light);     //writes the value of 'light' chosen by widget
}


void onTemperatureChange()
{

  temperature = dht.readTemperature();    //reads the temperature from sensor
                                          //the variable 'temperature' is automatically generated and declared by the cloud
}

void onHumidityChange()
{
  humidity = dht.readHumidity();      //reads humidity from sensor
                                      //the variable 'temperature' is automatically generated and declared by the cloud
}
